services:
  mysql:
    image: 'mysql:latest'
    container_name: 'MS-usuarios_bd'
    environment:
      - 'MYSQL_DATABASE=db_usuarios'
      - 'MYSQL_ROOT_PASSWORD=root'

    ports:
      - '3307:3306'

      #Actualmente estamos en entorno local, se desabilitaran estos parametros
      #- 'MYSQL_USER=admin'
      #- 'MYSQL_PASSWORD=root'
      